name: "SonarQube Scan - Cepsa"
description: "SonarQube Scanner"
author: "Cepsa"
branding:
  icon: "check"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  host:
    description: "SonarQube server URL"
    required: true
  login:
    description: "Login or authentication token of a SonarQube user"
    required: true
  password:
    description: "Password that goes with the sonar.login username"
    required: true
  projectBaseDir:
    description: "Set the sonar.projectBaseDir: Property to move analysis to a different directory"
    required: false
    default: "."    
